version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    environment:
      DB_USER: 'postgres'
      DB_HOST: 'db'
      DB_DATABASE: 'portfolio'
      DB_PASSWORD: 'portfolio'
      DB_PORT: '5432'
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'portfolio'
      POSTGRES_DB: 'portfolio'
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
